# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: jwt-introspect
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

brews:
  - name: jwt-introspect
    directory: Formula
    homepage: "https://github.com/roemu/jwt_introspect"
    description: "Web-developer tooling to extract values from JWT tokens."
    license: "GPL-3.0-or-later"
    repository:
      owner: roemu
      name: jwt_introspect
      branch: master

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
