# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JwtIntrospect < Formula
  desc "Web-developer tooling to extract values from JWT tokens."
  homepage "https://github.com/roemu/jwt_introspect"
  version "0.1.1"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roemu/jwt_introspect/releases/download/v0.1.1/jwt_introspect_Darwin_x86_64.tar.gz"
      sha256 "a5115f5e572aaa7b9570801b49ae96020caabf8646e0f599f981d1d67e289cb0"

      def install
        bin.install "jwt-introspect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roemu/jwt_introspect/releases/download/v0.1.1/jwt_introspect_Darwin_arm64.tar.gz"
      sha256 "84b75f8581a0d729d7d92396805cfaed4e40dac747ac702c77734b196bf31e04"

      def install
        bin.install "jwt-introspect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/roemu/jwt_introspect/releases/download/v0.1.1/jwt_introspect_Linux_x86_64.tar.gz"
        sha256 "7650b564b01292062c815e30eeb45f5f23a189ba2cd138cad757cbbf16fbaddd"

        def install
          bin.install "jwt-introspect"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/roemu/jwt_introspect/releases/download/v0.1.1/jwt_introspect_Linux_arm64.tar.gz"
        sha256 "75c90f12d134dafd316eb52ac327374ff4a98656a2d8b41b3ba08cfdc1ba0166"

        def install
          bin.install "jwt-introspect"
        end
      end
    end
  end
end
